### ISSUE TITLE
[Anon] Bug report: Genestealer_Cults.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-mobile-format#113]
**File:** Genestealer_Cults.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Purestrain Genestealers incorrect points value. Should be 10 points per model not 18 as of faq update. 

Sorry if this is already reported.

**Comment by Falco4077** [comment]
Their per model pts went up to 15 in the July errata. Also in case no one else has said so, their points cost for their talons dropped to 0.
