### ISSUE TITLE
Force Organisation

### ISSUE THREAD

**Issue by Psalmirot** [BSData/wh40k-mobile-format#143]
Hey, great work on creating this. I'm unsure whether this is something other people are seeing but when creating a new roster the force organisation cannot be changed when selecting multiple forces. For example selecting a battalion force organisation means that any additional rosters selected will only ever be able to select a battalion force organisation. Additionally the option of an unbound list does not seem to be available.
File: WH40k 8th Mobile format 1.1.1
BattleScribe version: 2.01.04
Platform: Windows
Dropbox: No

**Comment by Ponha** [comment]
As far as i know the unbound option is not added yet. I have not had the issue of having to add the same force as the first one selected. Make sure you do not have the old force selected when adding a new one.
