### ISSUE TITLE
[Join Request] Ponha would like to join the repository

### ISSUE THREAD

**Issue by Ponha** [BSData/wh40k-mobile-format#47]
Hi,

since I am a big fan of this project I would like to contribute to it. After reading through material in the BSdata wiki this seemed to be the prudent course of action. I have used battlescribe for a couple of years but only recently begun to modify files.

I would like to contribute to this project since I prefer the flat structure when building my own lists. My primary interest is to contribute to the Astra Militarum files at the moment.

**Comment by WindstormSCR** [comment]
Can you swing by the Gitter chatroom later so that we can talk about what stuff you wanted to contribute and to talk over details of how things need to be implemented? Thanks!
