### ISSUE TITLE
Imperium Index 1 Errata

### ISSUE THREAD

**Issue by WindstormSCR** [BSData/wh40k-mobile-format#50]
Make adjustments to account for changes in https://www.warhammer-community.com/2017/07/02/warhammer-40000-faq-now-available-july2gw-homepage-post-1/

**Comment by Ponha** [comment]
This was fixed in yesterdays pull request

**Comment by Ponha** [comment]
Sorry i closed this by mistake, I was looking to comment on the Imperium index 2 and screwed up
