### ISSUE TITLE
[Anon] Bug report: Questor_Traitoris.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-mobile-format#66]
**File:** Questor_Traitoris.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** FW Chaplain Venerable Dreadnought can't exchange DCCW for Dreadnought Inferno Cannon (option not given)

**Comment by lakides** [comment]
Sorry posted against wrong section. Meant for SM.
