### ISSUE TITLE
Venerable Dreadnought doesn't show it's Power level value

### ISSUE THREAD

**Issue by Guy-Markman** [BSData/wh40k-mobile-format#86]
I built a list with Venerable Dreadnought in it and I noticed that the Venerable Dreadnought doesn't show it's Power Level value

**Comment by Guy-Markman** [comment]
<a href="https://ibb.co/ixN7s5"><img src="https://preview.ibb.co/eEbBKk/IMG_0484.png" alt="IMG_0484" border="0"></a>

**Comment by WindstormSCR** [comment]
not all power levels are implemented, progress on profiles and power levels has been slow because of work taking up time I had intended to spend on this project. the space marine files will be receiving a complete re-write once I can get my hands on the new codex and find the time
